// Turns the Deadman pixel icon pack (assets/icons/*.svg, rectangles on a
// 12x12 grid) into PixelSprites for the DMIcon widget.
//
// dart run tool/gen_icons.dart
//
// Writes lib/ui/widgets/brand/dm_icons.g.dart and formats it. Rerun after
// adding or redrawing an icon; the enum order is fixed by [order] below.
import 'dart:io';

const source = 'assets/icons';
const target = 'lib/ui/widgets/brand/dm_icons.g.dart';
const grid = 12;

/// SVG file stems in enum order. Every SVG in [source] must be listed.
const order = [
  'wallet',
  'key',
  'warning',
  'swap',
  'cloak',
  'eye-off',
  'shield',
  'shield-z',
  'shield-plus',
  'plus',
  'history',
  'chevron-right',
  'lock',
  'logout',
  'pulse',
  'heartbeat',
  'users',
  'fingerprint',
  'calendar',
];

Future<void> main() async {
  final files = {
    for (final f in Directory(source).listSync().whereType<File>())
      if (f.path.endsWith('.svg'))
        f.uri.pathSegments.last.replaceAll('.svg', ''): f,
  };
  final missing = order.where((n) => !files.containsKey(n));
  final extra = files.keys.where((n) => !order.contains(n));
  if (missing.isNotEmpty || extra.isNotEmpty) {
    stderr.writeln(
      'missing: ${missing.join(', ')}; unlisted: ${extra.join(', ')}',
    );
    exit(1);
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_icons.dart from $source/*.svg.')
    ..writeln('// Do not edit by hand: redraw the SVG and rerun the tool.')
    ..writeln()
    ..writeln("import 'pixel_art.dart';")
    ..writeln()
    ..writeln(
      '/// The Deadman pixel icon pack (docs/brand/icons), one value per',
    )
    ..writeln('/// icon. Draw them with `DMIcon`.')
    ..writeln('enum DMIcons {');
  for (final name in order) {
    final icon = parse(name, files[name]!.readAsStringSync());
    final args = [
      if (icon.dx != 0) 'dx: ${literal(icon.dx)}',
      if (icon.dy != 0) 'dy: ${literal(icon.dy)}',
    ];
    out
      ..writeln('  ${camel(name)}(')
      ..writeln("    PixelSprite('$name', [")
      ..writeAll(icon.rows.map((r) => "      '$r',\n"))
      ..writeln('    ]),')
      ..writeAll(args.map((a) => '    $a,\n'))
      ..writeln('  ),');
  }
  out
    ..writeln('  ;')
    ..writeln()
    ..writeln('  const DMIcons(this.sprite, {this.dx = 0, this.dy = 0});')
    ..writeln()
    ..writeln('  /// Cells per side of every icon box.')
    ..writeln('  static const grid = $grid;')
    ..writeln()
    ..writeln('  final PixelSprite sprite;')
    ..writeln()
    ..writeln('  /// Where [sprite] sits inside the [grid] box, in cells. Only')
    ..writeln('  /// icons whose SVG viewBox is shifted (pulse) are off zero.')
    ..writeln('  final double dx;')
    ..writeln('  final double dy;')
    ..writeln('}');

  File(target).writeAsStringSync(out.toString());
  final fmt = await Process.run('dart', ['format', target]);
  if (fmt.exitCode != 0) {
    stderr.write(fmt.stderr);
    exit(fmt.exitCode);
  }
  stdout.writeln('wrote $target (${order.length} icons)');
}

typedef Icon = ({List<String> rows, double dx, double dy});

Icon parse(String name, String svg) {
  Never fail(String why) => throw FormatException('$name.svg: $why');

  final vb = RegExp(r'viewBox="([^"]+)"').firstMatch(svg)?.group(1);
  if (vb == null) fail('no viewBox');
  final [minX, minY, w, h] = vb
      .trim()
      .split(RegExp(r'[\s,]+'))
      .map(double.parse)
      .toList();
  if (w != grid || h != grid) fail('viewBox is ${w}x$h, want ${grid}x$grid');
  if (minX > 0 || minY > 0) fail('viewBox origin must be <= 0');

  final cells = <(int, int)>{};
  void fill(double x, double y, double rw, double rh) {
    if ([x, y, rw, rh].any((v) => v != v.roundToDouble())) {
      fail('rect $x,$y ${rw}x$rh is off the pixel grid');
    }
    for (var cy = y.toInt(); cy < y + rh; cy++) {
      for (var cx = x.toInt(); cx < x + rw; cx++) {
        if (cx < 0 || cy < 0 || cx + minX >= grid || cy + minY >= grid) {
          fail('cell $cx,$cy falls outside the viewBox');
        }
        cells.add((cx, cy));
      }
    }
  }

  for (final m in RegExp(r'<rect\b([^>]*)>').allMatches(svg)) {
    double attr(String a) => double.parse(
      RegExp('\\b$a="([^"]+)"').firstMatch(m.group(1)!)?.group(1) ?? '0',
    );
    fill(attr('x'), attr('y'), attr('width'), attr('height'));
  }

  for (final m in RegExp(r'<path\b[^>]*\bd="([^"]+)"').allMatches(svg)) {
    for (final poly in subpaths(m.group(1)!, fail)) {
      final xs = {for (final p in poly) p.$1};
      final ys = {for (final p in poly) p.$2};
      if (xs.length != 2 || ys.length != 2 || poly.length != 4) {
        fail('subpath ${poly.join(' ')} is not an axis-aligned rectangle');
      }
      final (x0, x1) = (xs.reduce(minD), xs.reduce(maxD));
      final (y0, y1) = (ys.reduce(minD), ys.reduce(maxD));
      fill(x0, y0, x1 - x0, y1 - y0);
    }
  }
  if (cells.isEmpty) fail('no filled cells');

  final width = (grid + minX).floor();
  final height = (grid + minY).floor();
  return (
    rows: [
      for (var y = 0; y < height; y++)
        [for (var x = 0; x < width; x++) cells.contains((x, y)) ? '#' : '.']
            .join(),
    ],
    dx: -minX,
    dy: -minY,
  );
}

double minD(double a, double b) => a < b ? a : b;
double maxD(double a, double b) => a > b ? a : b;

/// Vertex lists of each closed subpath in [d]. Supports the straight-line
/// commands (M L H V Z, absolute and relative).
List<List<(double, double)>> subpaths(String d, Never Function(String) fail) {
  final tokens = RegExp(r'[MmLlHhVvZz]|-?(?:\d+\.?\d*|\.\d+)')
      .allMatches(d)
      .map((m) => m.group(0)!)
      .toList();
  final result = <List<(double, double)>>[];
  var current = <(double, double)>[];
  var (x, y) = (0.0, 0.0);
  var (startX, startY) = (0.0, 0.0);
  String? cmd;
  var i = 0;
  double next() {
    if (i >= tokens.length) fail('path ends mid-command');
    return double.tryParse(tokens[i++]) ?? fail('expected a number in "$d"');
  }

  void close() {
    if (current.isEmpty) return;
    if (current.length > 1 && current.last == current.first) {
      current.removeLast();
    }
    result.add(current);
    current = [];
  }

  while (i < tokens.length) {
    if (RegExp(r'^[A-Za-z]$').hasMatch(tokens[i])) cmd = tokens[i++];
    switch (cmd) {
      case 'M' || 'm':
        close();
        final (nx, ny) = (next(), next());
        (x, y) = cmd == 'm' ? (x + nx, y + ny) : (nx, ny);
        (startX, startY) = (x, y);
        current.add((x, y));
        cmd = cmd == 'm' ? 'l' : 'L';
      case 'L':
        (x, y) = (next(), next());
        current.add((x, y));
      case 'l':
        final (nx, ny) = (next(), next());
        (x, y) = (x + nx, y + ny);
        current.add((x, y));
      case 'H':
        x = next();
        current.add((x, y));
      case 'h':
        x += next();
        current.add((x, y));
      case 'V':
        y = next();
        current.add((x, y));
      case 'v':
        y += next();
        current.add((x, y));
      case 'Z' || 'z':
        close();
        (x, y) = (startX, startY);
        cmd = null;
      default:
        fail('unsupported path command "${tokens[i]}"');
    }
  }
  close();
  return result;
}

String literal(double v) => v == v.roundToDouble() ? '${v.toInt()}' : '$v';

String camel(String stem) => stem.replaceAllMapped(
  RegExp(r'-([a-z])'),
  (m) => m.group(1)!.toUpperCase(),
);
