// Turns the Boney mascot exports (docs/brand/v3-assets/04-boney-mascot:
// one SVG per state, rectangles on a 26x24 grid, plus the 5-frame idle
// GIF) into PixelSprites for the Boney widget.
//
// dart run tool/gen_boney.dart
//
// Writes lib/ui/widgets/brand/boney_sprites.g.dart and formats it. The GIF
// is matched cell for cell against boney-front.svg, so a frame that does
// not sit on the SVG grid fails the run instead of drawing blurry.
import 'dart:io';
import 'dart:typed_data';

import 'gen_icons.dart' show camel, maxD, minD, subpaths;

const source = 'docs/brand/v3-assets/04-boney-mascot';
const target = 'lib/ui/widgets/brand/boney_sprites.g.dart';
const gridW = 26;
const gridH = 24;

/// SVG stems in enum order.
const poses = [
  'front',
  'checked-in',
  'on-track',
  'check-in-soon',
  'missed',
  'tier-due',
  'last-tier',
  'no-plan',
  'released-ghost',
];

/// What each idle GIF frame shows, in order.
const idleNames = ['front', 'wink', 'wink, arm up', 'happy, arms up', 'wink'];

Future<void> main() async {
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_boney.dart from $source.')
    ..writeln('// Do not edit by hand: re-export the art and rerun the tool.')
    ..writeln()
    ..writeln("import 'pixel_art.dart';")
    ..writeln()
    ..writeln('/// One flat-colour layer of a Boney drawing; [argb] is the')
    ..writeln("/// layer's colour in the export (the first layer is Boney).")
    ..writeln('typedef BoneyLayer = ({PixelSprite sprite, int argb});')
    ..writeln()
    ..writeln('/// Boney in each state of the brand board, every one on the')
    ..writeln('/// same ${gridW}x$gridH grid so they swap in place.')
    ..writeln('enum BoneyPose {');
  List<String>? front;
  for (final name in poses) {
    final layers = parseLayers(
      name,
      File('$source/svg/boney-$name.svg').readAsStringSync(),
    );
    if (name == 'front') front = layers.first.rows;
    out.writeln('  ${camel(name)}([');
    for (final l in layers) {
      out
        ..writeln("    (sprite: PixelSprite('boney-$name', [")
        ..writeAll(l.rows.map((r) => "      '$r',\n"))
        ..writeln(
          "    ]), argb: 0x${l.argb.toRadixString(16).toUpperCase()}),",
        );
    }
    out.writeln('  ]),');
  }
  out
    ..writeln('  ;')
    ..writeln()
    ..writeln('  const BoneyPose(this.layers);')
    ..writeln()
    ..writeln('  final List<BoneyLayer> layers;')
    ..writeln('}')
    ..writeln()
    ..writeln('/// The idle loop (boney-idle.gif), drawn in the status colour.')
    ..writeln('const boneyIdle = <({PixelSprite sprite, int ms})>[');

  final gif = decodeGif(File('$source/boney-idle.gif').readAsBytesSync());
  final frames = gridFrames(gif, front!);
  if (frames.length != idleNames.length) {
    fail(
      'boney-idle.gif has ${frames.length} frames, want ${idleNames.length}',
    );
  }
  for (final (i, f) in frames.indexed) {
    out
      ..writeln('  // ${idleNames[i]}')
      ..writeln("  (sprite: PixelSprite('boney-idle-$i', [")
      ..writeAll(f.rows.map((r) => "    '$r',\n"))
      ..writeln('  ]), ms: ${f.ms}),');
  }
  out.writeln('];');

  File(target).writeAsStringSync(out.toString());
  final fmt = await Process.run('dart', ['format', target]);
  if (fmt.exitCode != 0) {
    stderr.write(fmt.stderr);
    exit(fmt.exitCode);
  }
  stdout.writeln(
    'wrote $target (${poses.length} poses, ${frames.length} frames)',
  );
}

Never fail(String why) => throw FormatException(why);

typedef Layer = ({List<String> rows, int argb});

/// One layer per `<path fill>` of a Boney SVG, in document order.
List<Layer> parseLayers(String name, String svg) {
  final vb = RegExp(r'viewBox="([^"]+)"').firstMatch(svg)?.group(1);
  if (vb != '0 0 $gridW $gridH') fail('$name.svg: viewBox is "$vb"');
  final layers = <Layer>[];
  for (final m in RegExp(r'<path\b([^>]*)>').allMatches(svg)) {
    final attrs = m.group(1)!;
    final d = RegExp(r'\bd="([^"]+)"').firstMatch(attrs)?.group(1);
    final fill = RegExp(r'\bfill="#([0-9A-Fa-f]{6})"').firstMatch(attrs);
    if (d == null || fill == null) fail('$name.svg: path without d or fill');
    final cells = <(int, int)>{};
    for (final poly in subpaths(d, (why) => fail('$name.svg: $why'))) {
      final xs = {for (final p in poly) p.$1};
      final ys = {for (final p in poly) p.$2};
      if (xs.length != 2 || ys.length != 2 || poly.length != 4) {
        fail('$name.svg: subpath ${poly.join(' ')} is not a rectangle');
      }
      final (x0, x1) = (xs.reduce(minD), xs.reduce(maxD));
      final (y0, y1) = (ys.reduce(minD), ys.reduce(maxD));
      if ([x0, x1, y0, y1].any((v) => v != v.roundToDouble())) {
        fail('$name.svg: rect off the pixel grid');
      }
      for (var y = y0.toInt(); y < y1; y++) {
        for (var x = x0.toInt(); x < x1; x++) {
          if (x >= gridW || y >= gridH) fail('$name.svg: cell $x,$y outside');
          cells.add((x, y));
        }
      }
    }
    layers.add((
      rows: [
        for (var y = 0; y < gridH; y++)
          [for (var x = 0; x < gridW; x++) cells.contains((x, y)) ? '#' : '.']
              .join(),
      ],
      argb: 0xFF000000 | int.parse(fill.group(1)!, radix: 16),
    ));
  }
  if (layers.isEmpty) fail('$name.svg: no layers');
  return layers;
}

/// A composited GIF frame: RGB (or null = transparent) per pixel.
typedef GifFrame = ({int w, int h, List<int?> rgb, int ms});

/// Each GIF frame mapped onto the SVG grid: cells are found from frame 0,
/// which must be [front] exactly. Only the frame's foreground colour (the
/// most used one) counts; tinted socket fills are holes, as in the SVGs.
List<({List<String> rows, int ms})> gridFrames(
  List<GifFrame> frames,
  List<String> front,
) {
  final f0 = frames.first;
  final ink = _mostUsed(f0.rgb);
  (int, int, int, int) bbox(GifFrame f) {
    var (x0, y0, x1, y1) = (f.w, f.h, -1, -1);
    for (var y = 0; y < f.h; y++) {
      for (var x = 0; x < f.w; x++) {
        if (f.rgb[y * f.w + x] != ink) continue;
        if (x < x0) x0 = x;
        if (y < y0) y0 = y;
        if (x > x1) x1 = x;
        if (y > y1) y1 = y;
      }
    }
    return (x0, y0, x1, y1);
  }

  var (fx0, fy0, fx1, fy1) = (gridW, gridH, -1, -1);
  for (var y = 0; y < gridH; y++) {
    for (var x = 0; x < gridW; x++) {
      if (front[y][x] != '#') continue;
      if (x < fx0) fx0 = x;
      if (y < fy0) fy0 = y;
      if (x > fx1) fx1 = x;
      if (y > fy1) fy1 = y;
    }
  }
  final (gx0, gy0, gx1, _) = bbox(f0);
  final cell = (gx1 - gx0 + 1) ~/ (fx1 - fx0 + 1);
  if (cell < 1 || (gx1 - gx0 + 1) % (fx1 - fx0 + 1) != 0) {
    fail('boney-idle.gif: frame 0 does not scale boney-front.svg evenly');
  }
  final ox = gx0 - fx0 * cell;
  final oy = gy0 - fy0 * cell;

  final out = <({List<String> rows, int ms})>[];
  for (final (i, f) in frames.indexed) {
    bool on(int x, int y) =>
        x >= 0 && y >= 0 && x < f.w && y < f.h && f.rgb[y * f.w + x] == ink;
    final (bx0, by0, bx1, by1) = bbox(f);
    if (bx0 < ox ||
        by0 < oy ||
        bx1 >= ox + gridW * cell ||
        by1 >= oy + gridH * cell) {
      fail('boney-idle.gif: frame $i leaves the ${gridW}x$gridH grid');
    }
    final rows = <String>[];
    for (var r = 0; r < gridH; r++) {
      final row = StringBuffer();
      for (var c = 0; c < gridW; c++) {
        final filled = on(ox + c * cell, oy + r * cell);
        for (var dy = 0; dy < cell; dy++) {
          for (var dx = 0; dx < cell; dx++) {
            if (on(ox + c * cell + dx, oy + r * cell + dy) != filled) {
              fail('boney-idle.gif: frame $i cell $c,$r is not one colour');
            }
          }
        }
        row.write(filled ? '#' : '.');
      }
      rows.add(row.toString());
    }
    if (i == 0 && rows.join() != front.join()) {
      fail('boney-idle.gif: frame 0 differs from boney-front.svg');
    }
    out.add((rows: rows, ms: f.ms));
  }
  return out;
}

int _mostUsed(List<int?> rgb) {
  final counts = <int, int>{};
  for (final c in rgb) {
    if (c != null) counts[c] = (counts[c] ?? 0) + 1;
  }
  return counts.entries.reduce((a, b) => a.value >= b.value ? a : b).key;
}

/// Minimal GIF89a decoder: global/local palettes, transparency, frame
/// delays and the "restore to background" disposal the export uses.
List<GifFrame> decodeGif(Uint8List b) {
  var p = 0;
  int u8() => b[p++];
  int u16() => b[p++] | (b[p++] << 8);
  if (String.fromCharCodes(b.sublist(0, 6)) case != 'GIF89a' && != 'GIF87a') {
    fail('not a GIF');
  }
  p = 6;
  final w = u16(), h = u16();
  final flags = u8();
  p += 2; // background index, aspect
  List<int>? palette(int f) {
    if (f & 0x80 == 0) return null;
    final n = 1 << ((f & 7) + 1);
    final pal = [
      for (var i = 0; i < n; i++)
        (b[p + i * 3] << 16) | (b[p + i * 3 + 1] << 8) | b[p + i * 3 + 2],
    ];
    p += n * 3;
    return pal;
  }

  final global = palette(flags);
  final canvas = List<int?>.filled(w * h, null);
  final frames = <GifFrame>[];
  var delay = 0;
  int? transparent;
  var disposal = 0;
  (int, int, int, int)? clearRect;

  Uint8List blocks() {
    final data = BytesBuilder();
    for (var n = u8(); n != 0; n = u8()) {
      data.add(b.sublist(p, p + n));
      p += n;
    }
    return data.toBytes();
  }

  while (p < b.length) {
    switch (u8()) {
      case 0x21:
        final label = u8();
        final data = blocks();
        if (label == 0xF9 && data.length >= 4) {
          disposal = (data[0] >> 2) & 7;
          delay = data[1] | (data[2] << 8);
          transparent = data[0] & 1 == 1 ? data[3] : null;
        }
      case 0x2C:
        if (clearRect case (final x0, final y0, final cw, final ch)) {
          for (var y = y0; y < y0 + ch && y < h; y++) {
            for (var x = x0; x < x0 + cw && x < w; x++) {
              canvas[y * w + x] = null;
            }
          }
          clearRect = null;
        }
        final x0 = u16(), y0 = u16(), fw = u16(), fh = u16();
        final f = u8();
        if (f & 0x40 != 0) fail('interlaced GIF frames are not supported');
        final pal = palette(f) ?? global ?? fail('GIF without a palette');
        final minCode = u8();
        final idx = _lzw(blocks(), minCode, fw * fh);
        for (var i = 0; i < idx.length; i++) {
          if (idx[i] == transparent) continue;
          final x = x0 + i % fw, y = y0 + i ~/ fw;
          if (x < w && y < h) canvas[y * w + x] = pal[idx[i]];
        }
        frames.add((w: w, h: h, rgb: List.of(canvas), ms: delay * 10));
        if (disposal == 2) clearRect = (x0, y0, fw, fh);
        if (disposal == 3) fail('GIF "restore to previous" is not supported');
        transparent = null;
        disposal = 0;
        delay = 0;
      case 0x3B:
        return frames;
      default:
        fail('bad GIF block at $p');
    }
  }
  return frames;
}

List<int> _lzw(Uint8List data, int minCode, int count) {
  final clear = 1 << minCode, end = clear + 1;
  var size = minCode + 1;
  var dict = <List<int>>[
    for (var i = 0; i < clear; i++) [i],
    [],
    [],
  ];
  final out = <int>[];
  List<int>? prev;
  var bitPos = 0;
  int read() {
    var v = 0;
    for (var i = 0; i < size; i++) {
      final byte = (bitPos + i) >> 3;
      if (byte >= data.length) return end;
      v |= ((data[byte] >> ((bitPos + i) & 7)) & 1) << i;
    }
    bitPos += size;
    return v;
  }

  while (out.length < count) {
    final code = read();
    if (code == clear) {
      size = minCode + 1;
      dict = dict.sublist(0, end + 1);
      prev = null;
      continue;
    }
    if (code == end) break;
    List<int> entry;
    if (code < dict.length) {
      entry = dict[code];
      if (prev != null) dict.add([...prev, entry.first]);
    } else if (prev != null && code == dict.length) {
      entry = [...prev, prev.first];
      dict.add(entry);
    } else {
      fail('corrupt GIF LZW stream');
    }
    out.addAll(entry);
    prev = entry;
    if (dict.length == 1 << size && size < 12) size++;
  }
  return out;
}
