//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: deadman
// ----------------------------------------------------------------------------
pub mod deadman {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for deadman
    pub fn program_id() -> Pubkey {
        pubkey!("ACHVLMoLDM3YPpGbNST4cZW4Tf2jx6nzJGuusyLJHofL")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AcceptAdmin
    // ....................................................................

    /// Main instruction struct for AcceptAdmin
    pub struct AcceptAdminInstruction {
        pub accounts: AcceptAdminInstructionAccountMetas,
        pub data: AcceptAdminInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AcceptAdmin instruction
    #[derive(Debug, Clone, Default)]
    pub struct AcceptAdminInstructionAccountMetas {
        pub new_admin: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for AcceptAdmin instruction
    #[derive(Debug, Clone)]
    pub struct AcceptAdminInstructionAccounts {
        pub new_admin: Pubkey,

        pub config: Pubkey,
    }

    impl AcceptAdminInstructionAccounts {
        pub fn new(new_admin: Pubkey, config: Pubkey) -> Self {
            Self { new_admin, config }
        }
    }

    /// Instruction data for AcceptAdmin
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AcceptAdminInstructionData {}

    impl AcceptAdminInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for AcceptAdminInstruction
    impl AcceptAdminInstruction {
        fn discriminator() -> [u8; 8] {
            [112u8, 42u8, 45u8, 90u8, 116u8, 181u8, 13u8, 170u8]
        }

        pub fn data(data: AcceptAdminInstructionData) -> Self {
            Self {
                accounts: AcceptAdminInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AcceptAdminInstructionAccounts) -> Self {
            self.accounts.new_admin = AccountMeta::new_readonly(accounts.new_admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.new_admin.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CloseVault
    // ....................................................................

    /// Main instruction struct for CloseVault
    pub struct CloseVaultInstruction {
        pub accounts: CloseVaultInstructionAccountMetas,
        pub data: CloseVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CloseVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct CloseVaultInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,

        pub rent_payer: AccountMeta,
    }

    /// Account pubkeys for CloseVault instruction
    #[derive(Debug, Clone)]
    pub struct CloseVaultInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,

        pub rent_payer: Pubkey,
    }

    impl CloseVaultInstructionAccounts {
        pub fn new(owner: Pubkey, vault: Pubkey, rent_payer: Pubkey) -> Self {
            Self {
                owner,

                vault,

                rent_payer,
            }
        }
    }

    /// Instruction data for CloseVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CloseVaultInstructionData {}

    impl CloseVaultInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CloseVaultInstruction
    impl CloseVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [141u8, 103u8, 17u8, 126u8, 72u8, 75u8, 29u8, 29u8]
        }

        pub fn data(data: CloseVaultInstructionData) -> Self {
            Self {
                accounts: CloseVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CloseVaultInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.rent_payer = AccountMeta::new(accounts.rent_payer, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.rent_payer.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreatePlan
    // ....................................................................

    /// Main instruction struct for CreatePlan
    pub struct CreatePlanInstruction {
        pub accounts: CreatePlanInstructionAccountMetas,
        pub data: CreatePlanInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreatePlan instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreatePlanInstructionAccountMetas {
        pub owner: AccountMeta,

        pub payer: AccountMeta,

        pub vault: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreatePlan instruction
    #[derive(Debug, Clone)]
    pub struct CreatePlanInstructionAccounts {
        pub owner: Pubkey,

        pub payer: Pubkey,

        pub vault: Pubkey,
    }

    impl CreatePlanInstructionAccounts {
        pub fn new(owner: Pubkey, payer: Pubkey, vault: Pubkey) -> Self {
            Self {
                owner,

                payer,

                vault,
            }
        }
    }

    /// Instruction data for CreatePlan
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreatePlanInstructionData {
        pub plan_id: u16,

        pub label: String,

        pub guard: Pubkey,

        pub lock_secs: i64,

        pub skip_grace_secs: i64,

        pub rules: Vec<RuleInput>,
    }

    impl CreatePlanInstructionData {
        pub fn new(
            plan_id: u16,

            label: String,

            guard: Pubkey,

            lock_secs: i64,

            skip_grace_secs: i64,

            rules: Vec<RuleInput>,
        ) -> Self {
            Self {
                plan_id,

                label,

                guard,

                lock_secs,

                skip_grace_secs,

                rules,
            }
        }
    }

    /// Implementation for CreatePlanInstruction
    impl CreatePlanInstruction {
        fn discriminator() -> [u8; 8] {
            [77u8, 43u8, 141u8, 254u8, 212u8, 118u8, 41u8, 186u8]
        }

        pub fn data(data: CreatePlanInstructionData) -> Self {
            Self {
                accounts: CreatePlanInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreatePlanInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateVesting
    // ....................................................................

    /// Main instruction struct for CreateVesting
    pub struct CreateVestingInstruction {
        pub accounts: CreateVestingInstructionAccountMetas,
        pub data: CreateVestingInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateVesting instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateVestingInstructionAccountMetas {
        pub owner: AccountMeta,

        pub payer: AccountMeta,

        pub vault: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateVesting instruction
    #[derive(Debug, Clone)]
    pub struct CreateVestingInstructionAccounts {
        pub owner: Pubkey,

        pub payer: Pubkey,

        pub vault: Pubkey,
    }

    impl CreateVestingInstructionAccounts {
        pub fn new(owner: Pubkey, payer: Pubkey, vault: Pubkey) -> Self {
            Self {
                owner,

                payer,

                vault,
            }
        }
    }

    /// Instruction data for CreateVesting
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateVestingInstructionData {
        pub plan_id: u16,

        pub label: String,

        pub guard: Pubkey,

        pub lock_secs: i64,

        pub start_at: i64,

        pub revocable: bool,

        pub schedules: Vec<VestingInput>,

        pub period_secs: i64,
    }

    impl CreateVestingInstructionData {
        pub fn new(
            plan_id: u16,

            label: String,

            guard: Pubkey,

            lock_secs: i64,

            start_at: i64,

            revocable: bool,

            schedules: Vec<VestingInput>,

            period_secs: i64,
        ) -> Self {
            Self {
                plan_id,

                label,

                guard,

                lock_secs,

                start_at,

                revocable,

                schedules,

                period_secs,
            }
        }
    }

    /// Implementation for CreateVestingInstruction
    impl CreateVestingInstruction {
        fn discriminator() -> [u8; 8] {
            [135u8, 184u8, 171u8, 156u8, 197u8, 162u8, 246u8, 44u8]
        }

        pub fn data(data: CreateVestingInstructionData) -> Self {
            Self {
                accounts: CreateVestingInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateVestingInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ExecuteSolRule
    // ....................................................................

    /// Main instruction struct for ExecuteSolRule
    pub struct ExecuteSolRuleInstruction {
        pub accounts: ExecuteSolRuleInstructionAccountMetas,
        pub data: ExecuteSolRuleInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ExecuteSolRule instruction
    #[derive(Debug, Clone, Default)]
    pub struct ExecuteSolRuleInstructionAccountMetas {
        pub executor: AccountMeta,

        pub vault: AccountMeta,

        pub config: AccountMeta,

        pub beneficiary: AccountMeta,

        pub treasury: AccountMeta,
    }

    /// Account pubkeys for ExecuteSolRule instruction
    #[derive(Debug, Clone)]
    pub struct ExecuteSolRuleInstructionAccounts {
        pub executor: Pubkey,

        pub vault: Pubkey,

        pub config: Pubkey,

        pub beneficiary: Pubkey,

        pub treasury: Pubkey,
    }

    impl ExecuteSolRuleInstructionAccounts {
        pub fn new(
            executor: Pubkey,

            vault: Pubkey,

            config: Pubkey,

            beneficiary: Pubkey,

            treasury: Pubkey,
        ) -> Self {
            Self {
                executor,

                vault,

                config,

                beneficiary,

                treasury,
            }
        }
    }

    /// Instruction data for ExecuteSolRule
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ExecuteSolRuleInstructionData {
        pub index: u8,
    }

    impl ExecuteSolRuleInstructionData {
        pub fn new(index: u8) -> Self {
            Self { index }
        }
    }

    /// Implementation for ExecuteSolRuleInstruction
    impl ExecuteSolRuleInstruction {
        fn discriminator() -> [u8; 8] {
            [27u8, 74u8, 220u8, 147u8, 58u8, 73u8, 241u8, 103u8]
        }

        pub fn data(data: ExecuteSolRuleInstructionData) -> Self {
            Self {
                accounts: ExecuteSolRuleInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ExecuteSolRuleInstructionAccounts) -> Self {
            self.accounts.executor = AccountMeta::new_readonly(accounts.executor, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, false);

            self.accounts.treasury = AccountMeta::new(accounts.treasury, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.executor.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.treasury.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ExecuteTokenRule
    // ....................................................................

    /// Main instruction struct for ExecuteTokenRule
    pub struct ExecuteTokenRuleInstruction {
        pub accounts: ExecuteTokenRuleInstructionAccountMetas,
        pub data: ExecuteTokenRuleInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ExecuteTokenRule instruction
    #[derive(Debug, Clone, Default)]
    pub struct ExecuteTokenRuleInstructionAccountMetas {
        pub executor: AccountMeta,

        pub vault: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub vault_token: AccountMeta,

        pub beneficiary: AccountMeta,

        pub beneficiary_token: AccountMeta,

        pub treasury_token: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ExecuteTokenRule instruction
    #[derive(Debug, Clone)]
    pub struct ExecuteTokenRuleInstructionAccounts {
        pub executor: Pubkey,

        pub vault: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub vault_token: Pubkey,

        pub beneficiary: Pubkey,

        pub beneficiary_token: Pubkey,

        pub treasury_token: Pubkey,
    }

    impl ExecuteTokenRuleInstructionAccounts {
        pub fn new(
            executor: Pubkey,

            vault: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            vault_token: Pubkey,

            beneficiary: Pubkey,

            beneficiary_token: Pubkey,

            treasury_token: Pubkey,
        ) -> Self {
            Self {
                executor,

                vault,

                config,

                mint,

                vault_token,

                beneficiary,

                beneficiary_token,

                treasury_token,
            }
        }
    }

    /// Instruction data for ExecuteTokenRule
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ExecuteTokenRuleInstructionData {
        pub index: u8,
    }

    impl ExecuteTokenRuleInstructionData {
        pub fn new(index: u8) -> Self {
            Self { index }
        }
    }

    /// Implementation for ExecuteTokenRuleInstruction
    impl ExecuteTokenRuleInstruction {
        fn discriminator() -> [u8; 8] {
            [172u8, 93u8, 237u8, 201u8, 225u8, 26u8, 97u8, 140u8]
        }

        pub fn data(data: ExecuteTokenRuleInstructionData) -> Self {
            Self {
                accounts: ExecuteTokenRuleInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ExecuteTokenRuleInstructionAccounts) -> Self {
            self.accounts.executor = AccountMeta::new_readonly(accounts.executor, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.vault_token = AccountMeta::new(accounts.vault_token, false);

            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, false);

            self.accounts.beneficiary_token = AccountMeta::new(accounts.beneficiary_token, false);

            self.accounts.treasury_token = AccountMeta::new(accounts.treasury_token, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.executor.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault_token.clone());

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.beneficiary_token.clone());

            metas.push(self.accounts.treasury_token.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitConfig
    // ....................................................................

    /// Main instruction struct for InitConfig
    pub struct InitConfigInstruction {
        pub accounts: InitConfigInstructionAccountMetas,
        pub data: InitConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitConfigInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub treasury: AccountMeta,

        pub program: AccountMeta,

        pub program_data: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitConfig instruction
    #[derive(Debug, Clone)]
    pub struct InitConfigInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub treasury: Pubkey,

        pub program_data: Pubkey,
    }

    impl InitConfigInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey, treasury: Pubkey, program_data: Pubkey) -> Self {
            Self {
                admin,

                config,

                treasury,

                program_data,
            }
        }
    }

    /// Instruction data for InitConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitConfigInstructionData {
        pub skr_mint: Pubkey,
    }

    impl InitConfigInstructionData {
        pub fn new(skr_mint: Pubkey) -> Self {
            Self { skr_mint }
        }
    }

    /// Implementation for InitConfigInstruction
    impl InitConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [23u8, 235u8, 115u8, 232u8, 168u8, 96u8, 1u8, 231u8]
        }

        pub fn data(data: InitConfigInstructionData) -> Self {
            Self {
                accounts: InitConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitConfigInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.treasury = AccountMeta::new_readonly(accounts.treasury, false);

            self.accounts.program = AccountMeta::new_readonly(
                pubkey!("ACHVLMoLDM3YPpGbNST4cZW4Tf2jx6nzJGuusyLJHofL"),
                false,
            );

            self.accounts.program_data = AccountMeta::new_readonly(accounts.program_data, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.treasury.clone());

            metas.push(self.accounts.program.clone());

            metas.push(self.accounts.program_data.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Lockdown
    // ....................................................................

    /// Main instruction struct for Lockdown
    pub struct LockdownInstruction {
        pub accounts: LockdownInstructionAccountMetas,
        pub data: LockdownInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Lockdown instruction
    #[derive(Debug, Clone, Default)]
    pub struct LockdownInstructionAccountMetas {
        pub signer: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for Lockdown instruction
    #[derive(Debug, Clone)]
    pub struct LockdownInstructionAccounts {
        pub signer: Pubkey,

        pub vault: Pubkey,
    }

    impl LockdownInstructionAccounts {
        pub fn new(signer: Pubkey, vault: Pubkey) -> Self {
            Self { signer, vault }
        }
    }

    /// Instruction data for Lockdown
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct LockdownInstructionData {}

    impl LockdownInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for LockdownInstruction
    impl LockdownInstruction {
        fn discriminator() -> [u8; 8] {
            [21u8, 66u8, 102u8, 35u8, 233u8, 188u8, 139u8, 9u8]
        }

        pub fn data(data: LockdownInstructionData) -> Self {
            Self {
                accounts: LockdownInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: LockdownInstructionAccounts) -> Self {
            self.accounts.signer = AccountMeta::new_readonly(accounts.signer, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.signer.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ProposeAdmin
    // ....................................................................

    /// Main instruction struct for ProposeAdmin
    pub struct ProposeAdminInstruction {
        pub accounts: ProposeAdminInstructionAccountMetas,
        pub data: ProposeAdminInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ProposeAdmin instruction
    #[derive(Debug, Clone, Default)]
    pub struct ProposeAdminInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for ProposeAdmin instruction
    #[derive(Debug, Clone)]
    pub struct ProposeAdminInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,
    }

    impl ProposeAdminInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey) -> Self {
            Self { admin, config }
        }
    }

    /// Instruction data for ProposeAdmin
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ProposeAdminInstructionData {
        pub new_admin: Pubkey,
    }

    impl ProposeAdminInstructionData {
        pub fn new(new_admin: Pubkey) -> Self {
            Self { new_admin }
        }
    }

    /// Implementation for ProposeAdminInstruction
    impl ProposeAdminInstruction {
        fn discriminator() -> [u8; 8] {
            [121u8, 214u8, 199u8, 212u8, 87u8, 39u8, 117u8, 234u8]
        }

        pub fn data(data: ProposeAdminInstructionData) -> Self {
            Self {
                accounts: ProposeAdminInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ProposeAdminInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pulse
    // ....................................................................

    /// Main instruction struct for Pulse
    pub struct PulseInstruction {
        pub accounts: PulseInstructionAccountMetas,
        pub data: PulseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pulse instruction
    #[derive(Debug, Clone, Default)]
    pub struct PulseInstructionAccountMetas {
        pub signer: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for Pulse instruction
    #[derive(Debug, Clone)]
    pub struct PulseInstructionAccounts {
        pub signer: Pubkey,

        pub vault: Pubkey,
    }

    impl PulseInstructionAccounts {
        pub fn new(signer: Pubkey, vault: Pubkey) -> Self {
            Self { signer, vault }
        }
    }

    /// Instruction data for Pulse
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PulseInstructionData {}

    impl PulseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PulseInstruction
    impl PulseInstruction {
        fn discriminator() -> [u8; 8] {
            [192u8, 224u8, 96u8, 191u8, 190u8, 177u8, 63u8, 34u8]
        }

        pub fn data(data: PulseInstructionData) -> Self {
            Self {
                accounts: PulseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PulseInstructionAccounts) -> Self {
            self.accounts.signer = AccountMeta::new_readonly(accounts.signer, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.signer.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RecoverLegacyVault
    // ....................................................................

    /// Main instruction struct for RecoverLegacyVault
    pub struct RecoverLegacyVaultInstruction {
        pub accounts: RecoverLegacyVaultInstructionAccountMetas,
        pub data: RecoverLegacyVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RecoverLegacyVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct RecoverLegacyVaultInstructionAccountMetas {
        pub owner: AccountMeta,

        pub legacy: AccountMeta,
    }

    /// Account pubkeys for RecoverLegacyVault instruction
    #[derive(Debug, Clone)]
    pub struct RecoverLegacyVaultInstructionAccounts {
        pub owner: Pubkey,

        pub legacy: Pubkey,
    }

    impl RecoverLegacyVaultInstructionAccounts {
        pub fn new(owner: Pubkey, legacy: Pubkey) -> Self {
            Self { owner, legacy }
        }
    }

    /// Instruction data for RecoverLegacyVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RecoverLegacyVaultInstructionData {
        pub plan_id: u16,
    }

    impl RecoverLegacyVaultInstructionData {
        pub fn new(plan_id: u16) -> Self {
            Self { plan_id }
        }
    }

    /// Implementation for RecoverLegacyVaultInstruction
    impl RecoverLegacyVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [202u8, 5u8, 20u8, 4u8, 206u8, 216u8, 105u8, 134u8]
        }

        pub fn data(data: RecoverLegacyVaultInstructionData) -> Self {
            Self {
                accounts: RecoverLegacyVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RecoverLegacyVaultInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.legacy = AccountMeta::new(accounts.legacy, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.legacy.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ReleaseVestedSol
    // ....................................................................

    /// Main instruction struct for ReleaseVestedSol
    pub struct ReleaseVestedSolInstruction {
        pub accounts: ReleaseVestedSolInstructionAccountMetas,
        pub data: ReleaseVestedSolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ReleaseVestedSol instruction
    #[derive(Debug, Clone, Default)]
    pub struct ReleaseVestedSolInstructionAccountMetas {
        pub executor: AccountMeta,

        pub vault: AccountMeta,

        pub config: AccountMeta,

        pub beneficiary: AccountMeta,

        pub treasury: AccountMeta,
    }

    /// Account pubkeys for ReleaseVestedSol instruction
    #[derive(Debug, Clone)]
    pub struct ReleaseVestedSolInstructionAccounts {
        pub executor: Pubkey,

        pub vault: Pubkey,

        pub config: Pubkey,

        pub beneficiary: Pubkey,

        pub treasury: Pubkey,
    }

    impl ReleaseVestedSolInstructionAccounts {
        pub fn new(
            executor: Pubkey,

            vault: Pubkey,

            config: Pubkey,

            beneficiary: Pubkey,

            treasury: Pubkey,
        ) -> Self {
            Self {
                executor,

                vault,

                config,

                beneficiary,

                treasury,
            }
        }
    }

    /// Instruction data for ReleaseVestedSol
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ReleaseVestedSolInstructionData {
        pub index: u8,
    }

    impl ReleaseVestedSolInstructionData {
        pub fn new(index: u8) -> Self {
            Self { index }
        }
    }

    /// Implementation for ReleaseVestedSolInstruction
    impl ReleaseVestedSolInstruction {
        fn discriminator() -> [u8; 8] {
            [136u8, 188u8, 48u8, 45u8, 14u8, 211u8, 200u8, 228u8]
        }

        pub fn data(data: ReleaseVestedSolInstructionData) -> Self {
            Self {
                accounts: ReleaseVestedSolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ReleaseVestedSolInstructionAccounts) -> Self {
            self.accounts.executor = AccountMeta::new_readonly(accounts.executor, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, false);

            self.accounts.treasury = AccountMeta::new(accounts.treasury, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.executor.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.treasury.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ReleaseVestedToken
    // ....................................................................

    /// Main instruction struct for ReleaseVestedToken
    pub struct ReleaseVestedTokenInstruction {
        pub accounts: ReleaseVestedTokenInstructionAccountMetas,
        pub data: ReleaseVestedTokenInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ReleaseVestedToken instruction
    #[derive(Debug, Clone, Default)]
    pub struct ReleaseVestedTokenInstructionAccountMetas {
        pub executor: AccountMeta,

        pub vault: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub vault_token: AccountMeta,

        pub beneficiary: AccountMeta,

        pub beneficiary_token: AccountMeta,

        pub treasury_token: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ReleaseVestedToken instruction
    #[derive(Debug, Clone)]
    pub struct ReleaseVestedTokenInstructionAccounts {
        pub executor: Pubkey,

        pub vault: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub vault_token: Pubkey,

        pub beneficiary: Pubkey,

        pub beneficiary_token: Pubkey,

        pub treasury_token: Pubkey,
    }

    impl ReleaseVestedTokenInstructionAccounts {
        pub fn new(
            executor: Pubkey,

            vault: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            vault_token: Pubkey,

            beneficiary: Pubkey,

            beneficiary_token: Pubkey,

            treasury_token: Pubkey,
        ) -> Self {
            Self {
                executor,

                vault,

                config,

                mint,

                vault_token,

                beneficiary,

                beneficiary_token,

                treasury_token,
            }
        }
    }

    /// Instruction data for ReleaseVestedToken
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ReleaseVestedTokenInstructionData {
        pub index: u8,
    }

    impl ReleaseVestedTokenInstructionData {
        pub fn new(index: u8) -> Self {
            Self { index }
        }
    }

    /// Implementation for ReleaseVestedTokenInstruction
    impl ReleaseVestedTokenInstruction {
        fn discriminator() -> [u8; 8] {
            [50u8, 241u8, 129u8, 168u8, 233u8, 106u8, 179u8, 16u8]
        }

        pub fn data(data: ReleaseVestedTokenInstructionData) -> Self {
            Self {
                accounts: ReleaseVestedTokenInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ReleaseVestedTokenInstructionAccounts) -> Self {
            self.accounts.executor = AccountMeta::new_readonly(accounts.executor, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.vault_token = AccountMeta::new(accounts.vault_token, false);

            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, false);

            self.accounts.beneficiary_token = AccountMeta::new(accounts.beneficiary_token, false);

            self.accounts.treasury_token = AccountMeta::new(accounts.treasury_token, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.executor.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault_token.clone());

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.beneficiary_token.clone());

            metas.push(self.accounts.treasury_token.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RevokeVesting
    // ....................................................................

    /// Main instruction struct for RevokeVesting
    pub struct RevokeVestingInstruction {
        pub accounts: RevokeVestingInstructionAccountMetas,
        pub data: RevokeVestingInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RevokeVesting instruction
    #[derive(Debug, Clone, Default)]
    pub struct RevokeVestingInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for RevokeVesting instruction
    #[derive(Debug, Clone)]
    pub struct RevokeVestingInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,
    }

    impl RevokeVestingInstructionAccounts {
        pub fn new(owner: Pubkey, vault: Pubkey) -> Self {
            Self { owner, vault }
        }
    }

    /// Instruction data for RevokeVesting
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RevokeVestingInstructionData {}

    impl RevokeVestingInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RevokeVestingInstruction
    impl RevokeVestingInstruction {
        fn discriminator() -> [u8; 8] {
            [12u8, 252u8, 252u8, 168u8, 39u8, 101u8, 98u8, 9u8]
        }

        pub fn data(data: RevokeVestingInstructionData) -> Self {
            Self {
                accounts: RevokeVestingInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RevokeVestingInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetConfig
    // ....................................................................

    /// Main instruction struct for SetConfig
    pub struct SetConfigInstruction {
        pub accounts: SetConfigInstructionAccountMetas,
        pub data: SetConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetConfigInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub treasury: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for SetConfig instruction
    #[derive(Debug, Clone)]
    pub struct SetConfigInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub treasury: Pubkey,
    }

    impl SetConfigInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey, treasury: Pubkey) -> Self {
            Self {
                admin,

                config,

                treasury,
            }
        }
    }

    /// Instruction data for SetConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetConfigInstructionData {
        pub fee_bps_public: u16,

        pub fee_bps_private: u16,

        pub skr_mint: Pubkey,

        pub fee_bps_skr: u16,

        pub skr_burn_bps: u16,
    }

    impl SetConfigInstructionData {
        pub fn new(
            fee_bps_public: u16,

            fee_bps_private: u16,

            skr_mint: Pubkey,

            fee_bps_skr: u16,

            skr_burn_bps: u16,
        ) -> Self {
            Self {
                fee_bps_public,

                fee_bps_private,

                skr_mint,

                fee_bps_skr,

                skr_burn_bps,
            }
        }
    }

    /// Implementation for SetConfigInstruction
    impl SetConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [108u8, 158u8, 154u8, 175u8, 212u8, 98u8, 52u8, 66u8]
        }

        pub fn data(data: SetConfigInstructionData) -> Self {
            Self {
                accounts: SetConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetConfigInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.treasury = AccountMeta::new_readonly(accounts.treasury, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.treasury.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetGuard
    // ....................................................................

    /// Main instruction struct for SetGuard
    pub struct SetGuardInstruction {
        pub accounts: SetGuardInstructionAccountMetas,
        pub data: SetGuardInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetGuard instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetGuardInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for SetGuard instruction
    #[derive(Debug, Clone)]
    pub struct SetGuardInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,
    }

    impl SetGuardInstructionAccounts {
        pub fn new(owner: Pubkey, vault: Pubkey) -> Self {
            Self { owner, vault }
        }
    }

    /// Instruction data for SetGuard
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetGuardInstructionData {
        pub new_guard: Pubkey,
    }

    impl SetGuardInstructionData {
        pub fn new(new_guard: Pubkey) -> Self {
            Self { new_guard }
        }
    }

    /// Implementation for SetGuardInstruction
    impl SetGuardInstruction {
        fn discriminator() -> [u8; 8] {
            [250u8, 44u8, 173u8, 235u8, 219u8, 76u8, 36u8, 198u8]
        }

        pub fn data(data: SetGuardInstructionData) -> Self {
            Self {
                accounts: SetGuardInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetGuardInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SkipRule
    // ....................................................................

    /// Main instruction struct for SkipRule
    pub struct SkipRuleInstruction {
        pub accounts: SkipRuleInstructionAccountMetas,
        pub data: SkipRuleInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SkipRule instruction
    #[derive(Debug, Clone, Default)]
    pub struct SkipRuleInstructionAccountMetas {
        pub caller: AccountMeta,

        pub vault: AccountMeta,

        pub vault_token: AccountMeta,
    }

    /// Account pubkeys for SkipRule instruction
    #[derive(Debug, Clone)]
    pub struct SkipRuleInstructionAccounts {
        pub caller: Pubkey,

        pub vault: Pubkey,

        pub vault_token: Pubkey,
    }

    impl SkipRuleInstructionAccounts {
        pub fn new(caller: Pubkey, vault: Pubkey, vault_token: Pubkey) -> Self {
            Self {
                caller,

                vault,

                vault_token,
            }
        }
    }

    /// Instruction data for SkipRule
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SkipRuleInstructionData {
        pub index: u8,
    }

    impl SkipRuleInstructionData {
        pub fn new(index: u8) -> Self {
            Self { index }
        }
    }

    /// Implementation for SkipRuleInstruction
    impl SkipRuleInstruction {
        fn discriminator() -> [u8; 8] {
            [240u8, 82u8, 139u8, 70u8, 215u8, 222u8, 129u8, 174u8]
        }

        pub fn data(data: SkipRuleInstructionData) -> Self {
            Self {
                accounts: SkipRuleInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SkipRuleInstructionAccounts) -> Self {
            self.accounts.caller = AccountMeta::new_readonly(accounts.caller, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.vault_token = AccountMeta::new_readonly(accounts.vault_token, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.caller.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.vault_token.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Unlock
    // ....................................................................

    /// Main instruction struct for Unlock
    pub struct UnlockInstruction {
        pub accounts: UnlockInstructionAccountMetas,
        pub data: UnlockInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Unlock instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnlockInstructionAccountMetas {
        pub owner: AccountMeta,

        pub guardian: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for Unlock instruction
    #[derive(Debug, Clone)]
    pub struct UnlockInstructionAccounts {
        pub owner: Pubkey,

        pub guardian: Pubkey,

        pub vault: Pubkey,
    }

    impl UnlockInstructionAccounts {
        pub fn new(owner: Pubkey, guardian: Pubkey, vault: Pubkey) -> Self {
            Self {
                owner,

                guardian,

                vault,
            }
        }
    }

    /// Instruction data for Unlock
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnlockInstructionData {}

    impl UnlockInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnlockInstruction
    impl UnlockInstruction {
        fn discriminator() -> [u8; 8] {
            [101u8, 155u8, 40u8, 21u8, 158u8, 189u8, 56u8, 203u8]
        }

        pub fn data(data: UnlockInstructionData) -> Self {
            Self {
                accounts: UnlockInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnlockInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self.accounts.guardian = AccountMeta::new_readonly(accounts.guardian, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.guardian.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdatePlan
    // ....................................................................

    /// Main instruction struct for UpdatePlan
    pub struct UpdatePlanInstruction {
        pub accounts: UpdatePlanInstructionAccountMetas,
        pub data: UpdatePlanInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdatePlan instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdatePlanInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for UpdatePlan instruction
    #[derive(Debug, Clone)]
    pub struct UpdatePlanInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,
    }

    impl UpdatePlanInstructionAccounts {
        pub fn new(owner: Pubkey, vault: Pubkey) -> Self {
            Self { owner, vault }
        }
    }

    /// Instruction data for UpdatePlan
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdatePlanInstructionData {
        pub label: String,

        pub lock_secs: i64,

        pub skip_grace_secs: i64,

        pub rules: Vec<RuleInput>,

        pub guardian: Option<Pubkey>,
    }

    impl UpdatePlanInstructionData {
        pub fn new(
            label: String,

            lock_secs: i64,

            skip_grace_secs: i64,

            rules: Vec<RuleInput>,

            guardian: Option<Pubkey>,
        ) -> Self {
            Self {
                label,

                lock_secs,

                skip_grace_secs,

                rules,

                guardian,
            }
        }
    }

    /// Implementation for UpdatePlanInstruction
    impl UpdatePlanInstruction {
        fn discriminator() -> [u8; 8] {
            [119u8, 112u8, 58u8, 60u8, 76u8, 205u8, 1u8, 100u8]
        }

        pub fn data(data: UpdatePlanInstructionData) -> Self {
            Self {
                accounts: UpdatePlanInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdatePlanInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: WithdrawSol
    // ....................................................................

    /// Main instruction struct for WithdrawSol
    pub struct WithdrawSolInstruction {
        pub accounts: WithdrawSolInstructionAccountMetas,
        pub data: WithdrawSolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for WithdrawSol instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawSolInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for WithdrawSol instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawSolInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,
    }

    impl WithdrawSolInstructionAccounts {
        pub fn new(owner: Pubkey, vault: Pubkey) -> Self {
            Self { owner, vault }
        }
    }

    /// Instruction data for WithdrawSol
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawSolInstructionData {
        pub amount: u64,
    }

    impl WithdrawSolInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for WithdrawSolInstruction
    impl WithdrawSolInstruction {
        fn discriminator() -> [u8; 8] {
            [145u8, 131u8, 74u8, 136u8, 65u8, 137u8, 42u8, 38u8]
        }

        pub fn data(data: WithdrawSolInstructionData) -> Self {
            Self {
                accounts: WithdrawSolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawSolInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: WithdrawToken
    // ....................................................................

    /// Main instruction struct for WithdrawToken
    pub struct WithdrawTokenInstruction {
        pub accounts: WithdrawTokenInstructionAccountMetas,
        pub data: WithdrawTokenInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for WithdrawToken instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawTokenInstructionAccountMetas {
        pub owner: AccountMeta,

        pub vault: AccountMeta,

        pub mint: AccountMeta,

        pub vault_token: AccountMeta,

        pub owner_token: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for WithdrawToken instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawTokenInstructionAccounts {
        pub owner: Pubkey,

        pub vault: Pubkey,

        pub mint: Pubkey,

        pub vault_token: Pubkey,

        pub owner_token: Pubkey,

        pub token_program: Pubkey,
    }

    impl WithdrawTokenInstructionAccounts {
        pub fn new(
            owner: Pubkey,

            vault: Pubkey,

            mint: Pubkey,

            vault_token: Pubkey,

            owner_token: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                owner,

                vault,

                mint,

                vault_token,

                owner_token,

                token_program,
            }
        }
    }

    /// Instruction data for WithdrawToken
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawTokenInstructionData {
        pub amount: u64,
    }

    impl WithdrawTokenInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for WithdrawTokenInstruction
    impl WithdrawTokenInstruction {
        fn discriminator() -> [u8; 8] {
            [136u8, 235u8, 181u8, 5u8, 101u8, 109u8, 57u8, 81u8]
        }

        pub fn data(data: WithdrawTokenInstructionData) -> Self {
            Self {
                accounts: WithdrawTokenInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawTokenInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.vault_token = AccountMeta::new(accounts.vault_token, false);

            self.accounts.owner_token = AccountMeta::new(accounts.owner_token, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault_token.clone());

            metas.push(self.accounts.owner_token.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: AdminChanged
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AdminChanged {
    pub old_admin: Pubkey,

    pub new_admin: Pubkey,
}

impl AdminChanged {
    pub fn new(old_admin: Pubkey, new_admin: Pubkey) -> Self {
        Self {
            old_admin,

            new_admin,
        }
    }
}

/// Custom struct: AdminProposed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AdminProposed {
    pub admin: Pubkey,

    pub pending_admin: Pubkey,
}

impl AdminProposed {
    pub fn new(admin: Pubkey, pending_admin: Pubkey) -> Self {
        Self {
            admin,

            pending_admin,
        }
    }
}

/// Custom enum: AmountMode
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum AmountMode {
    Fixed,

    Percent,
}

/// Custom struct: Config
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Config {
    pub admin: Pubkey,

    pub treasury: Pubkey,

    pub fee_bps_public: u16,

    pub fee_bps_private: u16,

    pub bump: u8,

    pub skr_mint: Pubkey,

    pub fee_bps_skr: u16,

    pub skr_burn_bps: u16,

    pub pending_admin: Pubkey,

    pub _reserved: [u8; 64],
}

impl Config {
    pub fn new(
        admin: Pubkey,

        treasury: Pubkey,

        fee_bps_public: u16,

        fee_bps_private: u16,

        bump: u8,

        skr_mint: Pubkey,

        fee_bps_skr: u16,

        skr_burn_bps: u16,

        pending_admin: Pubkey,

        _reserved: [u8; 64],
    ) -> Self {
        Self {
            admin,

            treasury,

            fee_bps_public,

            fee_bps_private,

            bump,

            skr_mint,

            fee_bps_skr,

            skr_burn_bps,

            pending_admin,

            _reserved,
        }
    }
}

/// Custom struct: FeeBurned
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct FeeBurned {
    pub vault: Pubkey,

    pub mint: Pubkey,

    pub amount: u64,
}

impl FeeBurned {
    pub fn new(vault: Pubkey, mint: Pubkey, amount: u64) -> Self {
        Self {
            vault,

            mint,

            amount,
        }
    }
}

/// Custom struct: LegacyVaultRecovered
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct LegacyVaultRecovered {
    pub vault: Pubkey,

    pub owner: Pubkey,

    pub plan_id: u16,

    pub data_len: u32,

    pub lamports: u64,
}

impl LegacyVaultRecovered {
    pub fn new(vault: Pubkey, owner: Pubkey, plan_id: u16, data_len: u32, lamports: u64) -> Self {
        Self {
            vault,

            owner,

            plan_id,

            data_len,

            lamports,
        }
    }
}

/// Custom struct: LockedDown
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct LockedDown {
    pub vault: Pubkey,

    pub by: Pubkey,

    pub until: i64,
}

impl LockedDown {
    pub fn new(vault: Pubkey, by: Pubkey, until: i64) -> Self {
        Self { vault, by, until }
    }
}

/// Custom enum: PlanKind
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum PlanKind {
    Inheritance,

    Vesting,
}

/// Custom struct: PolicyUpdated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PolicyUpdated {
    pub vault: Pubkey,

    pub rules: u8,
}

impl PolicyUpdated {
    pub fn new(vault: Pubkey, rules: u8) -> Self {
        Self { vault, rules }
    }
}

/// Custom struct: Pulsed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Pulsed {
    pub vault: Pubkey,

    pub by: Pubkey,

    pub streak: u32,

    pub at: i64,
}

impl Pulsed {
    pub fn new(vault: Pubkey, by: Pubkey, streak: u32, at: i64) -> Self {
        Self {
            vault,

            by,

            streak,

            at,
        }
    }
}

/// Custom enum: Rail
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum Rail {
    Solana,

    Cloak,

    Zcash,
}

/// Custom struct: Rule
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Rule {
    pub beneficiary: Pubkey,

    pub rail: Rail,

    pub after_secs: i64,

    pub mint: Option<Pubkey>,

    pub mode: AmountMode,

    pub amount: u64,

    pub executed_at: i64,

    pub paid: u64,

    pub skipped_at: i64,

    pub reserved: u64,

    pub duration_secs: i64,

    pub released: u64,
}

impl Rule {
    pub fn new(
        beneficiary: Pubkey,

        rail: Rail,

        after_secs: i64,

        mint: Option<Pubkey>,

        mode: AmountMode,

        amount: u64,

        executed_at: i64,

        paid: u64,

        skipped_at: i64,

        reserved: u64,

        duration_secs: i64,

        released: u64,
    ) -> Self {
        Self {
            beneficiary,

            rail,

            after_secs,

            mint,

            mode,

            amount,

            executed_at,

            paid,

            skipped_at,

            reserved,

            duration_secs,

            released,
        }
    }
}

/// Custom struct: RuleExecuted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RuleExecuted {
    pub vault: Pubkey,

    pub index: u8,

    pub beneficiary: Pubkey,

    pub rail: Rail,

    pub mint: Option<Pubkey>,

    pub amount: u64,

    pub fee: u64,

    pub by: Pubkey,
}

impl RuleExecuted {
    pub fn new(
        vault: Pubkey,

        index: u8,

        beneficiary: Pubkey,

        rail: Rail,

        mint: Option<Pubkey>,

        amount: u64,

        fee: u64,

        by: Pubkey,
    ) -> Self {
        Self {
            vault,

            index,

            beneficiary,

            rail,

            mint,

            amount,

            fee,

            by,
        }
    }
}

/// Custom struct: RuleInput
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RuleInput {
    pub beneficiary: Pubkey,

    pub rail: Rail,

    pub after_secs: i64,

    pub mint: Option<Pubkey>,

    pub mode: AmountMode,

    pub amount: u64,
}

impl RuleInput {
    pub fn new(
        beneficiary: Pubkey,

        rail: Rail,

        after_secs: i64,

        mint: Option<Pubkey>,

        mode: AmountMode,

        amount: u64,
    ) -> Self {
        Self {
            beneficiary,

            rail,

            after_secs,

            mint,

            mode,

            amount,
        }
    }
}

/// Custom struct: RuleSkipped
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RuleSkipped {
    pub vault: Pubkey,

    pub index: u8,

    pub reserved: u64,

    pub by: Pubkey,
}

impl RuleSkipped {
    pub fn new(vault: Pubkey, index: u8, reserved: u64, by: Pubkey) -> Self {
        Self {
            vault,

            index,

            reserved,

            by,
        }
    }
}

/// Custom struct: Unlocked
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Unlocked {
    pub vault: Pubkey,

    pub at: i64,
}

impl Unlocked {
    pub fn new(vault: Pubkey, at: i64) -> Self {
        Self { vault, at }
    }
}

/// Custom struct: Vault
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Vault {
    pub owner: Pubkey,

    pub plan_id: u16,

    pub guard: Pubkey,

    pub guardian: Option<Pubkey>,

    pub _reserved_interval: [u8; 8],

    pub lock_secs: i64,

    pub skip_grace_secs: i64,

    pub last_pulse: i64,

    pub owner_last_seen: i64,

    pub locked_until: i64,

    pub guardian_ready_at: i64,

    pub total_pulses: u64,

    pub streak: u32,

    pub best_streak: u32,

    pub kind: PlanKind,

    pub start_at: i64,

    pub revocable: bool,

    pub revoked_at: i64,

    pub rent_payer: Pubkey,

    pub rent_paid: u64,

    pub rules: Vec<Rule>,

    pub label: String,

    pub bump: u8,

    pub stipend_paid: u8,

    pub vest_period_secs: i64,

    pub _reserved: [u8; 55],
}

impl Vault {
    pub fn new(
        owner: Pubkey,

        plan_id: u16,

        guard: Pubkey,

        guardian: Option<Pubkey>,

        _reserved_interval: [u8; 8],

        lock_secs: i64,

        skip_grace_secs: i64,

        last_pulse: i64,

        owner_last_seen: i64,

        locked_until: i64,

        guardian_ready_at: i64,

        total_pulses: u64,

        streak: u32,

        best_streak: u32,

        kind: PlanKind,

        start_at: i64,

        revocable: bool,

        revoked_at: i64,

        rent_payer: Pubkey,

        rent_paid: u64,

        rules: Vec<Rule>,

        label: String,

        bump: u8,

        stipend_paid: u8,

        vest_period_secs: i64,

        _reserved: [u8; 55],
    ) -> Self {
        Self {
            owner,

            plan_id,

            guard,

            guardian,

            _reserved_interval,

            lock_secs,

            skip_grace_secs,

            last_pulse,

            owner_last_seen,

            locked_until,

            guardian_ready_at,

            total_pulses,

            streak,

            best_streak,

            kind,

            start_at,

            revocable,

            revoked_at,

            rent_payer,

            rent_paid,

            rules,

            label,

            bump,

            stipend_paid,

            vest_period_secs,

            _reserved,
        }
    }
}

/// Custom struct: VaultCreated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct VaultCreated {
    pub vault: Pubkey,

    pub owner: Pubkey,

    pub plan_id: u16,

    pub rules: u8,
}

impl VaultCreated {
    pub fn new(vault: Pubkey, owner: Pubkey, plan_id: u16, rules: u8) -> Self {
        Self {
            vault,

            owner,

            plan_id,

            rules,
        }
    }
}

/// Custom struct: VestingInput
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct VestingInput {
    pub beneficiary: Pubkey,

    pub rail: Rail,

    pub mint: Option<Pubkey>,

    pub total: u64,

    pub cliff_secs: i64,

    pub duration_secs: i64,
}

impl VestingInput {
    pub fn new(
        beneficiary: Pubkey,

        rail: Rail,

        mint: Option<Pubkey>,

        total: u64,

        cliff_secs: i64,

        duration_secs: i64,
    ) -> Self {
        Self {
            beneficiary,

            rail,

            mint,

            total,

            cliff_secs,

            duration_secs,
        }
    }
}

/// Custom struct: VestingRevoked
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct VestingRevoked {
    pub vault: Pubkey,

    pub at: i64,
}

impl VestingRevoked {
    pub fn new(vault: Pubkey, at: i64) -> Self {
        Self { vault, at }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
